### PR TITLE
Further simplify and explain winding calculation in getWinding()

### PR DESCRIPTION
**Pull request by iconexperience**
Further simplify and explain winding calculation in getWinding()

### CODE REVIEW

**Comment by iconexperience** [comment]
Closing this because I forgot to change `countCrossing` to `countIntersection`. Will create a new pull request.

**Comment by lehni** [comment]
Great! For future reference, there is no need to close a pull-request and open a new one when all you want to do is add changes. Simply commit the new change to your fork and they should show up here as second commits. And that's completely fine, i do amendments on my commits all the time:

http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by iconexperience** [comment]
Thanks, I will keep that in mind (still learning)

**Comment by lehni** [comment]
No worries! Just thought you might find it good to know, as it lowers the threshold for PRs.

And really great work, as always!!

**Pull request closed without merging**
