### PR TITLE
Bug fix SvgExport.js

### PR DESCRIPTION
**Pull request by jmostaer**
Missing arguments in function call to getDefinitions

### CODE REVIEW

**Comment by lehni** [comment]
What bug is this fixing? Could you tell me a scenario / provide a test-case where this is causing issues?

**Comment by jmostaer** [comment]
If getDefinition is called without arguments (which sometimes happens when calling paper.project.importSVG) this line inside the getDefinition function will throw an exception since item is undefined:

var id = item._id || item.__id || (item.__id = UID.get('svg'));

**Comment by lehni** [comment]
Which version are you using? I believe we already fixed that bug in the `develop` branch.

**Comment by jmostaer** [comment]
I'm using the version on the master branch. Develop seems to be fixed indeed when looking at the code differences.

**Pull request closed without merging**
