### PR TITLE
Add rough bounds checking for _addBounds()

### PR DESCRIPTION
**Pull request by iconexperience**
Performance of `_addBounds()` can be improved significantly by performing a rough bounds checking first. This is a cheap way to check if the curve can extend the current min or max values at all. Only if the current bounds can be extended by the curve's bounds, further calculation needs to be done.
Also, if the values of a curve are sorted, the extrema are simply the start and end point.

### CODE REVIEW

**Comment by lehni** [comment]
Looks good. A suggestion though:

Instead of writing a long description into the commit message (those should stay short and concise) it's better to add it as a code comment to the actual block of code.

And when indenting code, please note that we don't let code go over 80 chars. If you're using Sublime Text, there's a great plugin to treat comments automatically, down to the formatting of @param & co: https://github.com/ehuss/Sublime-Wrap-Plus

**Comment by lehni** [comment]
This one broke jshinting, because `function add(value, padding)` is inside a block now. Will fix it shortly:

`W082  Line 801, Col 13  Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.`

**Comment by lehni** [comment]
But hey, really great optimization!

**Comment by iconexperience** [comment]
Yep, this has quite an effect. Regarding the function I actually wasn't sure where to place it correctly, so I am not too surprised something in the tool chain complained.

**Comment by lehni** [comment]
Inner functions are supposed to be outside of any scopes, not exactly sure why, but that's what the linters want, so we comply :)

**Pull request merged**
