### PR TITLE
node-canvas createJPG--> createJPEG

### PR DESCRIPTION
**Pull request by therewasaguy**
I'm trying to create JPG's with paper.js in node, but the node-canvas API requires an "e" in the spelling of JPEG.

### CODE REVIEW

**Comment by therewasaguy** [comment]
Added `extension` option to `createFrames`. It defaults to `png` but with [this](https://github.com/paperjs/paper.js/pull/1166/commits/37d066add13fe67d9739c17d83fb22e7d4e6afd0) `jpg` is an option.

```
paper.view.exportFrames({
        amount: 10,
        directory: '/tmp',
        prefix: '',
        padding: 3,
        extension: 'jpg',
        onComplete: function() {
          //...
        }
    });
```

**Comment by simonemazzoni** [comment]
Hello @lehni ,
why this PR hasn't been merged yet?
I faced the same problem regarding `jpegStream` and `createJPEGStream` and I was about to fix the bug and send a PR but then I saw this one which is exactly what I did in my branch to fix the bug.

Could you please merge this?

Another question: I tried to rebuild my branch and use it as NPM source to test the fix in my project, but I noticed that `.gitignore` contains the `/dist/*/` which prevent the push of the `/dist/node` folder containing all the node-canvas stuff, making the release unusable since it lacks the node part.
Could you please tell me how you deploy the library to also include that part? I tried to follow the instructions, but that .gitignore entry breaks all.

Thanks.
Simone

**Comment by hbar-digital** [comment]
I'm having the same issue. Would be nice to get this merged.

**Comment by therewasaguy** [comment]
let me know if there's anything I can do!

**Comment by lehni** [comment]
I'm sorry for the silence here and elsewhere, been swamped with work and couldn't find time to look after Paper.js in months... I hope for this to change again soon.

**Comment by simonemazzoni** [comment]
@lehni good to hear that! :)

Could you just explain to me how to compile paperjs for distribution? So as I can temporarily use my own branch.

Thanks

**Comment by lehni** [comment]
Does `gulp dist` not work, as described in the README?

**Comment by simonemazzoni** [comment]
Well, it works partially as I said before. It creates the `paper-core.js` and `paper-full.js` but it doesn't create the `node/` folder which contain all the server-side stuff.

The dist folder on you github repo lacks the node folder too, but if I `npm install paper` from npmjs, the node folder appear.

**Comment by lehni** [comment]
The `build:copy` task copies `src/node/*.js` to `dist/node`. It's a dependency of the `build` task, which is a dependency of the `dist` task. I don't know why it doesn't seem to get copied on your system. What version of Node are you using? Mac, Windows or Linux?

**Comment by simonemazzoni** [comment]
@hbar-digital yes I know, I already managed to solve that problem. As I said, the task works, but doesn't create the `node/` folder which contains all the server-side stuff.

@lehni currently I'm using nodejs v6.11.2. Anyway the task itself creates the `/node` folder correctly, but the `.gitignore` contains a line to ignore that folder, hence the `dist/node` folder isn't pushed in my repo, so when I set my repo url as npm source ( `npm install https://github.com/simonemazzoni/paper.js.git#my-branch-with-fix` ) to install my paper.js branch, it doesn't download the `/node` folder.

**Comment by lehni** [comment]
@simonemazzoni why don't you change the content of `. gitignore` in your repo then?

**Comment by simonemazzoni** [comment]
@lehni I can and I will but, you know, I was thinking that maybe there were a more appropriate way since the package installed from your official repo has all the parts. :)

**Comment by lehni** [comment]
@simonemazzoni this is finally merged.

**Comment by lehni** [comment]
@therewasaguy I've slightly changed the way this is handled, see 6c5f1dc671df2c5f3cf12f12c9cddb2d9bc32366

I hope you approve.

**Comment by simonemazzoni** [comment]
Great!! Thanks for the good work! 🎉

**Comment by hbar-digital** [comment]
@lehni is it possible to get a new build/release out?

**Comment by lehni** [comment]
@hbar-digital done: https://www.npmjs.com/package/paper

**Pull request closed without merging**
