### PR TITLE
Improve performance of _getMonoCurves() by filtering more curves

### PR DESCRIPTION
**Pull request by iconexperience**
Curves are always monotone in y direction if the y coordinates of their end points and control points are sorted (yP1 >= yC1 >= yC2 >= yP2 or yP1 <= yC1 <= yC2 <= yP2). Performing this check is very cheap compared to the actual finding of extrema in y direction.

In my test case about 75% of the yet unfiltered curves can be filtered.

### CODE REVIEW

**Comment by lehni** [comment]
Very cool! Will merge right away : )

**Comment by lehni** [comment]
Unrelated, but perhaps useful. Did you see this?

https://guides.github.com/introduction/flow/

**Comment by iconexperience** [comment]
Thanks, will read. Was there anything unusual with my pull request (except for the boolean op on the wrong line :) )?

**Comment by lehni** [comment]
No, not at all! That's what I meant with "not implying anything" : )

**Comment by iconexperience** [comment]
Good. I feel I am getting better, but there is still a long way...

**Pull request merged**
