### PR TITLE
Improve-addCurveIntersections()

### PR DESCRIPTION
**Pull request by iconexperience**
In addCurveIntersections() handle cases where tDiff==0, some smaller changes and improvements

### CODE REVIEW

**Comment by iconexperience** [comment]
I also changed the condition for subdiving the curve to the condition recommended in the original Sederberg/Nishita algorithm (tDiff > 0.8). This makes the oldTDiff argument unnecessary, but I left it in there because I did not want to change the internal api befor e we have tested the new condition with the old edge cases..

**Comment by iconexperience** [comment]
I had to replace `tDiff > Numerical.EPSILON` with `tDiff > 0` to make the example in #859 work. I have not found any negative side effects on our big test case, but I admit the whole algorithm is still a bit shaky.

**Comment by lehni** [comment]
Thanks! I will have a close look tomorrow.

Looking quickly through the diff view, I realized something that I've seen before, and should maybe point out: There are quite a few changes that are just reformatting of existing code and don't relate to the actual fix. It would be better to refrain from such reformatting for a couple of reasons: The code currently follows a convention that's in place across the library and has its reasons to be the way it is, but mainly these changes make it harder to find out what actually changed functionally. Do you know what I mean?

**Comment by iconexperience** [comment]
Yes, maybe I should have split this into two. But changing the order of the conditions (which is the biggest change) has a functional reason, which is avoiding unnecessary curve splitting if an intersection may already be found. This is in lines 1475 to 1490, which has only been moved up.

The changes for the fix are actually the last `else if`and `else` statements and the introduction of `v1New`, which was necessary to have access to the original `v1` at the end.

Other changes are:
- changing `t` to `u`. This is only cosmetic and makes understanding the code a bit easier.
- simplifying all those calculations of average parameter values (for example `t = tMinNew + (tMaxNew - tMinNew) / 2` to `t = (tMinNew + tMaxNew) / 2`)
- changing the condition for curve splitting to `tDiff > 0.8`. This could have been done later.

And all those changes to comment indents were not intentional. I will try to take better care on that.

**Comment by iconexperience** [comment]
@lehni I will replace this pull request with two others, so we have the bugfix separated from the other code improvements.

**Comment by iconexperience** [comment]
Closing this as #863 and #864 have been created as replacements. Changing the condition for subdividing the curve from `tDiff > 0.5 && oldTDiff > 0.5` to  `tDiff > 0.8` is not covered by the replacements. This can be done later once we have more tests for edge cases.

**Pull request closed without merging**
