### PR TITLE
Use correct value for y 45 degree tangent

### PR DESCRIPTION
**Pull request by iconexperience**
I got the pythagoras wrong when I wrote this code. The length of the tangent vector is 1, therefore the y component is sqrt(0.5) for 45°. This will not make any difference, but still we should use the correct value.

image

### CODE REVIEW

**Comment by lehni** [comment]
Yes that make sense. We could use this instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/SQRT1_2

**Comment by iconexperience** [comment]
I did not even know that existed. It's definitely better, even though precision is not important here.

**Comment by lehni** [comment]
Precision isn't, but understanding is better : )
We could also do `new Point({ angle: 45, length: 1 }).y` : )

**Comment by iconexperience** [comment]
Uhm, yes, we could do that...

**Comment by iconexperience** [comment]
Closed and reopened this pull request to trigger a Travis-CI rebuild. This time all checks have passed.

**Comment by lehni** [comment]
Thanks! : )

**Pull request merged**
