### PR TITLE
Replace nodejs version 5 to 6 in Travis

### PR DESCRIPTION
**Pull request by sapics**
This PR would not change any features.

Currently, nodejs stable version is v7.
To support  active version, I wish to add v6 to Travis.
I guess that it is not necessary to test in v5.
https://github.com/nodejs/LTS#nodejs-long-term-support-working-group

### CODE REVIEW

**Comment by lehni** [comment]
@sapics there are a bunch of unrelated changes in this PR. I am going to merge this in, but usually it's best to keep this separate. Also, I'll still add Node 5 to the tests as well, and will eventually remove Node 4 after another year or so...

**Comment by sapics** [comment]
Sorry about it. I'll be more careful to make separate.

**Comment by bmacnaughton** [comment]
It might make sense to track node support to the LTS road map:

https://github.com/nodejs/LTS

**Comment by lehni** [comment]
@bmacnaughton good point!

**Pull request merged**
