### PR TITLE
Add links to changelog

### PR DESCRIPTION
**Pull request by SteamWind**
### Description

Added links to the last version changelog

### CODE REVIEW

**Comment by lehni** [comment]
Why? This will add unnecessary labor keeping the change-log up to speed. I'm not going to do so.

**Comment by SteamWind** [comment]
Okay I understand. I though it could help people to quickly relate to the quoted issue. I didn't though about time maintaining it.

**Comment by lehni** [comment]
Thanks for the help! For what it's worth: I copy the Change-log into each release on Github, and there the links work automatically:

https://github.com/paperjs/paper.js/releases

**Comment by SteamWind** [comment]
Oh okay, I didn't saw that... Thanks

**Pull request closed without merging**
