### PR TITLE
Add support for converting Rasters to jpeg DataURL

### PR DESCRIPTION
**Pull request by alecdhuse**
Added support for converting Rasters to jpeg DataURL via an options
variable.

### CODE REVIEW

**Comment by alecdhuse** [comment]
I did find out this can be accomplished by getting the canvas object from the raster and calling its toDataURL function with the jpeg option.

You may want to disregard this pull request.

**Comment by sapics** [comment]
:+1: 

I want this feature too!

I guess that
```diff
- if (!options.quality) {
-   //default quality used by most browsers
-   options.quality = 0.92;
- }

- if ((options.type !== "image/jpeg") && (options.type !== "image/png")) {
-   //Default to image/png if options.type is an unknown type
-   options.type = "image/png";
- }

- return canvas ? canvas.toDataURL(options.type, options.quality) : null;
+ return canvas ? canvas.toDataURL(options.type, options.quality || 0.92) : null;
```
looks better for file-size and there are some possibilities that a user want to use image/webp and so on.

**Comment by alecdhuse** [comment]
@sapics Your code does look much better.

**Comment by sapics** [comment]
@alecdhuse Thanks!

I think that this pr makes paper.js much useful!
When authors of paperjs are agree with this pr, i guess that we need to make a pr to `paperjs/develop`.

**Comment by lehni** [comment]
Yes this does look good! A PR towards the develop branch would be much appreciated indeed.

**Pull request closed without merging**
