### PR TITLE
Update README.md to include epic sax guy warning

### PR DESCRIPTION
**Pull request by HarrisonB**

### CODE REVIEW

**Comment by HarrisonB** [comment]
Hmm... this is very strange considering I only edited the README.

**Comment by lehni** [comment]
Let's try this route first: https://twitter.com/paperjs/status/778324856240832512

**Comment by lehni** [comment]
New attempt: https://github.com/kmakblob/paperjs/issues/1

**Comment by Jolg42** [comment]
I opened an issue on Bower's registry and they deregistered it 😉 
See https://github.com/bower/registry/issues/278
This issue can be closed now.

**Pull request closed without merging**
