### PR TITLE
Change addCurveIntersections() to fix #859

### LINKED ISSUE #859: Intersection not found on crossing curves
Although the boolean code looks fairly stable now, there are still cases that do not work. In this simple example `path.subtract()` yields in a wrong result.

```javascript
var p1 = new Path({segments:[
    [230, 360, 0, 0, 0, 0],
    [326.04999999999995, 361.95, 0,0, 7.100000000000023, 5.300000000000011],
    [347.74999999999994, 377.3, -7.300000000000011, -5, 0,0],
    [260, 400],
], closed:true});
var p2 = new Path({segments:[
   [329.8373529833907, 360.99927475751736, 0, 0, -0.5084518552435497, 1.7136677994218417],
    [327.9816245617005, 366.0401044369074, 0.7293957729680756, -1.645975116174725, 0, 0],
    [300, 380]
], closed:true});
var r = p1.subtract(p2);
p1.fillColor = 'rgba(255, 0, 0, .2)';
p2.fillColor = 'rgba(0, 0, 255, .2)';
r.fullySelected = true;
```

<a href="http://sketch.paperjs.org/#S/fVLbTuMwEP2VKC8UKR15bI8nLuKJH1iJx9KHNDVQkSaVky4CxL/vuKE0C4hRFCvHZy7nTN7yttqFfJHfPoWhfsyLvO426ftvFbM9ZtdZG56zP9XwOHvrw8MutEO/WN7FuzaTWGqjisw4eZ2fVfF5bbQDZf05KLER0qkKITOgmoQ2RUZgphDitJ5l4Gk9K/WYQdLm/DVPsLHNpIBOo1r1Aa2KrG66PmwWQzyE98urBB6F69+FizAPpWFD2pfGeMVHF0Am0myZmJCNOzkyV0CqtIQlkbaGrBc6AqNxjllEaCwt8n++MfgSnbbkkJU62pasVKisNU4ainIFrL3xxHK4UjFJxzmCs+RlAJRMy5q+L0WlnZVq9asFURzYI/SH9RCrepjt9Xgn2P22aW66pkuUi/iwrmaa6CQW9OXFSNQ/EEfOkf5JjHB/aJqX29CEeggb4aZRxkG24Rleu24noDkjtSwjpKIR1t2h3fQfyNVJ4xjyM69jqJ723VaWly+Wq/d/">Here is the sketch</a>

Here is how it looks (the two paths at the left, the actual sketch with the result selected at the right):

image

Slightly changing a handle (by .1) in the first path gives a correct result. <a href="http://sketch.paperjs.org/#S/fVLLTsMwEPyVKJcWKV35td44iBM/gMSx9JCmplSkSeWkIKj676wb+uChrqJYGY/HO7PZpU259mmRPr76vnpJs7RqF/H7rQzJRiZ3SePfk4eyfxnvOr9c+6bviulTeGoSrqnSIku05df5mWWnba0sCOPOhZEtIa4iYzIBvxC0uCgpLxUMAV0qGFYgAp0lE/p9jrFB+EJAxeaM+IZmWVLVbecXRR+2fn9zG8GDVXXdKltxkGvSqFyutRN08A3ckSJDSChJ22MGEwEocoMyR1RGo3FMl0BSW0vEJpTMjaQfSRG4XFpl0EoS4hBUDE9IYYy2fCE7F0DKaYfEi80FId84kWANOm5A8klDCv+OQcQp5WJ2NYLACWwkdNt5H8qqH2/UsMfY86qu79u6jZRRWM7LsUI8mgV1MxqI6h/iwDnQT8QAz9u6/nj0ta96v2BubGVoZOXf4bNt1wzqM1LxMHwUDTBvt82i+0Zujx6H4t93Hnz5umlXPLy0mM72Xw==">Here is the sketch</a>

### PR DESCRIPTION
**Pull request by iconexperience**
Change addCurveIntersections() to handle cases when tDiff == 0

### CODE REVIEW

**Comment by lehni** [comment]
Your pull requests all look good, but I am going to wait until I have implemented further tests for the intersection and boolean code, hopefully in the coming days (as soon as I get my taxes done : )

**Comment by iconexperience** [comment]
Yes, please wait with this one. I have further looked at the algorithm and maybe there is a better way to handle this,but the edge cases are a bit difficult to understand.

**Comment by lehni** [comment]
After accepting #864, this PR now has conflicts...

**Comment by iconexperience** [comment]
That's why they were originally combined in one pull-request :wink:

Please keep this open, I am currently taking another close look at fat line clipping, again with a little more understanding on what is going on.

**Comment by lehni** [comment]
This one's not ready to merge yet, right?

**Comment by iconexperience** [comment]
Yes, not ready. But I hope we can close fat line clipping once and for all this week.

**Comment by lehni** [comment]
One thing regarding branches and pull requests. It would be good to follow branch naming conventions for topic branches: https://github.com/agis-/git-style-guide#branches

I prefer: as specific as possible, all lowercase, separated with dash, and no special characters (avoid #).

e.g. `issue-859-fat-line-fix`

**Comment by iconexperience** [comment]
@lehni Alright, please merge this pull request. I fully understand that you do not enjoy running into issues that could be fixed by this, If I find a better solution, I can create a new pull request later.

**Comment by lehni** [comment]
Argh merging this properly is a real pain, since I applied #864 first.

**Comment by iconexperience** [comment]
Should I write a new pull request?

**Comment by lehni** [comment]
I'll figure it out...

**Comment by lehni** [comment]
Does the code form here onwards look OK to you now?

https://github.com/paperjs/paper.js/blob/issue-859-fat-line-clipping/src/path/Curve.js#L1469

**Comment by iconexperience** [comment]
Looks alright to me.

**Comment by lehni** [comment]
I found some minor optimization: df24de0fdf6f1f7333d270c698c299be38531093

Alright with you?

**Comment by iconexperience** [comment]
moving the v1Clip into the else block? Very good!

**Comment by lehni** [comment]
Yes that's the main change.

**Comment by iconexperience** [comment]
If I can still suggest a change:

`// Clip P with the fat-line for Q` is not really correct there. The clipping has been done before, now we are applying the clipping result to v1.

**Comment by lehni** [comment]
Thanks! I've addressed that in 9404c5a0e32ec198bb7af75294d9b2bbc64140fc

**Pull request merged**
