### PR TITLE
Remove unnecessary calculation

### PR DESCRIPTION
**Pull request by sapics**
I guess that `if` condition is deletable, isn't it?

### CODE REVIEW

**Comment by lehni** [comment]
Haha, nice catch. Yeah it sure looks like it is! But I'd like to ask @hkrish first to find out why it was there to begin with. Perhaps the comparison was meant to be performed with MACHINE_EPSILON tolerance?

**Comment by lehni** [comment]
@hkrish, could you have a look at this one please? Thanks!

**Comment by hkrish** [comment]
Good catch! That is unnecessary.

**Comment by lehni** [comment]
Sweet : )

**Pull request merged**
