### PR TITLE
Optimized handling of non-crossing boolean ops

### PR DESCRIPTION
**Pull request by iconexperience**
Addresses #1113

### CODE REVIEW

**Comment by iconexperience** [comment]
@lehni This seems to work quite well, but I am sure you have your own idea on how the function should be included in the whole boolean operation handling. Feel free to modify anything you want.

**Comment by lehni** [comment]
Great, thanks! I will look into merging this with `reorient()` also. That's still a possibility, right?

**Comment by iconexperience** [comment]
@lehni Yes, that is the intention. I think the algorithm works, what is missing is a structure that permits reusing part of the algorithm.

**Comment by lehni** [comment]
Closing due to https://github.com/paperjs/paper.js/issues/1113#issuecomment-277470850

**Pull request closed without merging**
