### PR TITLE
Update CHANGELOG.md for next version

### PR DESCRIPTION
**Pull request by sapics**
### Description

I update CHANGELOG.md for next version.

Add: #1532 fixes the bug which was created in `prebuilt version` not in `v0.11.5`. Therefore, I do not write down about it.

### CODE REVIEW

**Comment by lehni** [comment]
This looks good! There has been more in the meantime... @sapics @sasensi I wonder if each feature / fox should also directly add the line to the changelog? It would probably be easier on the long run to do it this way?

**Comment by sasensi** [comment]
Oops, I didn't saw it :)
Ok, I'll create another one soon.

**Comment by sapics** [comment]
There are some auto CHANGELOG.md generator like [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator).
I think that it is one of the options.
I have created it in UglifyJS2 https://github.com/mishoo/UglifyJS2/pull/3262.
You can review it in https://github.com/sapics/UglifyJS2/blob/changelog/CHANGELOG.md

**Comment by sapics** [comment]
I am afraid that to make a PR with CHANGELOG.md changes.
It is very difficult for me to explain in English... not crystal clear :_) Please try to read :)

1. Create a PR with CHANGELOG.md commit.
2. New version released, it means that `Prebuilt` line is replaced to `0.11.6` in CHANGELOG.md.
3. When you merge pull request in 1 **after released `0.11.6`**, I guess that the changelog will update towards **`0.11.6`** not `Prebuilt`, isn't it?

**Pull request merged**
