### PR TITLE
Fix for #960 - Shortcut Curve.evaluate() for t === 1

### PR DESCRIPTION
**Pull request by iconexperience**
Shortcut Curve.evaluate() for t === 1 to avoid imprecision.

### CODE REVIEW

**Comment by iconexperience** [comment]
So was this me or are there problems with Travis?

**Comment by lehni** [comment]
No it's failing currently anyway. In the middle of a big refactoring here...

**Comment by iconexperience** [comment]
OK, good to know. I will keep the issues and pull requests coming.  Just ignore them while you are busy.

**Comment by lehni** [comment]
Sounds good! As a rule of thumb, if Travis CI is already failing on the development branch, then you probably didn't cause the break in the PR : )

**Pull request merged**
