### PR TITLE
updated changelog

### PR DESCRIPTION
**Pull request by bmacnaughton**
Minor edits and updates to CHANGELOG.md

### CODE REVIEW

**Comment by lehni** [comment]
It looks good, but I don't understand why there are two commits, of which one says "	Merge pull request #1 from bmacnaughton/bmacnaughton-changelog-01 … Update through commit f60c984.2016-01-15"?

**Comment by lehni** [comment]
There are a couple errors in there that were hard to deduct from the commits, and a few purely internal things that I would remove again. Also, it would be good to wrap all code, classes included, in the `` ``

**Comment by bmacnaughton** [comment]
The first commit was me testing a pull request against my own repository just to see how it worked. Sorry to miss the `ClassNames` - I tried to put quote code appropriate but apparently missed a few.

I erred on the side of including things - I knew that there were a few that were appeared to be internal. I figured it was easier for you to remove things than to know they were missing.

**Comment by bmacnaughton** [comment]
I can take a stab at fixing if you'd like - `Color` and the names of the legacy constructors get backticks. Remove:

= Move `Tool#_fireEvent()` into private function in `Tool#_handleEvent()`.

- Add `getSquaredLineLength()` (removed `getEndDistanceSquared()`)

- `ctx.currentPath` caching optimization

Sometimes it is tough to tease out whether a commit is a change or is a fix required by a change or is just an optimization. I looked at the diffs and sometimes the code for most of the commits in order to try to deduce what was what. E.g., there were a lot of what appeared to be minor fixes related to the significant mouse handling changes.

The one area that I didn't feel like I captured well was the `event.preventDefault()` handling. It seemed like there were two different things going on - making preventing the default the new default, returning false to cause the default, but also returning true to prevent the default. I'm not sure how to capture that set of changes succintly.

**Comment by lehni** [comment]
Yeah I completely understand that these things are hard to figure out. Don't worry about `preventDefault()`. It's really good to have those in the list, even if the formulation is not ideal yet, so I can go through it later and brush it up. It's somehow really tricky to think of the change-log while in developer mode... I'm terrible and switching hats, it turns out. But quite good at staying in the zone for long periods of time : )

**Comment by bmacnaughton** [comment]
Yes, you stay in the zone for prodigious periods of time.

**Comment by lehni** [comment]
I just realized that paper.js has 666 closed issues. Not a good moment for a break : )

**Comment by lehni** [comment]
Here's a suggestion: Why don't we keep this PR open, and you can keep adding to it until I am ready to merge it in and release?

**Comment by bmacnaughton** [comment]
Works for me.

**Pull request closed without merging**
