### PR TITLE
Fix travis build failing

### PR DESCRIPTION
**Pull request by sasensi**
### Description
This is a fake commit aiming to trigger a travis build at a state where it should be passing.

#### Related pull request

- Relates to #1574
- relates to #1570

### Checklist

- [x] Code conforms with the JSHint rules (`npm run jshint` passes)

### CODE REVIEW

**Comment by sasensi** [comment]
@lehni, it seems that build failure is not related to code changes otherwise this one should pass.

**Comment by sasensi** [comment]
Actually, in this PR, I removed everything that had changed so there is no more reference to `CanvasProvider`, that's what is strange.

**Comment by lehni** [comment]
ha, yes! strange indeed!

**Comment by lehni** [comment]
but let me try something in the other branch...

**Comment by sasensi** [comment]
It's like if travis don't use updated code, I'm trying to reproduce it locally executing every commands of the build to see.

**Comment by sasensi** [comment]
Another clue: I restarted the last succeeding build to see what will happen and it failed too (https://travis-ci.org/paperjs/paper.js/jobs/441557562) so there is definitely a problem with travis scope.

**Comment by lehni** [comment]
@sasensi let's see how my new commit is doing. If it passes, we can close this.

**Comment by sasensi** [comment]
@lehni, this didn't passed as I expected, but not for the same reason, which is good thing, you just have to apply other part of the correction here #1574 about native classes.

**Comment by lehni** [comment]
@sasensi I've merged it. Let's see how this goes :)

**Comment by sasensi** [comment]
@lehni, yeah, I hope this time is the one ! :)
I'm pretty sure now that travis is not running tests against pull requests code. For the moment, I don't know why but I'll investigate.

**Comment by sasensi** [comment]
It passed ! 🎉
Sorry about making the build crash... again... :)
But I've learned a new thing: that tests needs to be run in built context.
And that until we've found what going on, we cannot trust travis PR build.

**Comment by lehni** [comment]
Bingo! 🎉 Hey and no worries at all. You can make it crash all you like, we just have to figure out what's causing it then :)

**Pull request closed without merging**
