### PR TITLE
Further simplify and explain winding calculation in getWinding() (2)

### PR DESCRIPTION
**Pull request by iconexperience**
Further simplify and explain winding calculation in getWinding()

### CODE REVIEW

**Comment by lehni** [comment]
Merging and tweaking things a bit right now.

**Comment by lehni** [comment]
I've left some comments in d186c2d35626c8a9a8922d656bd5c1767d9c2419 regarding coding guidelines.

**Comment by lehni** [comment]
Here's another code compression we could do... Not sure how readable it would be though (I don't struggle with these, but many people do):

```js
var x = py === yStart
    ? values[0]
    : py === yEnd
    ? values[6]
    : Curve.solveCubic(values, 1, py, roots, 0, 1) === 1
    ? Curve.getPoint(values, roots[0]).x
    : null;
```

**Comment by lehni** [comment]
Or like this, if it helps reading (I think it does):

```js
var x = py === yStart ? values[0]
    :   py === yEnd   ? values[6]
    : Curve.solveCubic(values, 1, py, roots, 0, 1) === 1
        ? Curve.getPoint(values, roots[0]).x
        : null;
```

Ternary Operators FTW!

**Comment by iconexperience** [comment]
Yep, that is nice (I prefer the second snipplet). If people want to understand how winding calculation works, they should know ternary  operators :)

**Comment by lehni** [comment]
:+1: :)

**Pull request merged**
